services:
  - type: web
    name: gpt-mail-generator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --chdir=/opt/render/project/src"
    flask==2.3.2





